version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: .env

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wordpress:/var/www/html
      # - /path/to/myTheme:/var/www/html/wp-content/themes/myTheme # 別リポジトリでテーマ開発をする場合
    ports: 
      - "5000:80" # localhost:5000 でアクセス（適宜修正してください）
    restart: always
    env_file: .env

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 5001:80 # localhost:5001 でアクセス（適宜修正してください）
    restart: always
    env_file: .env

volumes:
  db_data: